tasks:
  - init: npm install && npm run db:init && npm run db:seed
    command: npm start

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-vscode.vscode-json